title: Jekyll SEO Tag
description: A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content.

permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title:
  - DG Community
  -dg community
  
  
  
  author:
   - Saichethan
   
   social:
     name: DG Community
     
     links:
       https://m.facebook.com/DG-Community-IIIT-Bhagalpur-177777156160101
     
