title: DG Community
description: Official Website of Developers Group : IIIT Bhagalpur

permalink: /index.html

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

title:
  - DG Community
  -dg community
  
  
  
  author:
   - Saichethan
   
   social:
     name: DG Community
     
     links:
       https://m.facebook.com/DG-Community-IIIT-Bhagalpur-177777156160101
     
webmaster_verifications:
  google: google168f402f18521927.html 
